# Generated by Django 4.2.1 on 2023-07-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_joinresultodds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinresultodds',
            name='horse_name',
        ),
        migrations.RemoveField(
            model_name='joinresultodds',
            name='race_name',
        ),
    ]
