# Generated by Django 4.2.1 on 2023-07-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_gamerace_gameracehorse_remove_gameresult_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameracehorse',
            old_name='Game',
            new_name='GameRace',
        ),
    ]
