# Generated by Django 4.2.1 on 2023-08-02 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_user_alter_comment_uid_alter_vote_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorsePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GameRace',
            new_name='Race',
        ),
        migrations.RenameModel(
            old_name='GameRaceHorse',
            new_name='Horse',
        ),
        migrations.CreateModel(
            name='RaceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.race')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='GameComment',
        ),

        migrations.RenameField(
            model_name='vote',
            old_name='Game',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='UID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='GameRace',
        ),
        migrations.RemoveField(
            model_name='gamerule',
            name='rule_end_datetime',
        ),
        migrations.RemoveField(
            model_name='gamerule',
            name='rule_start_datetime',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='GameRace',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='horse_id_first',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='horse_id_second',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='horse_id_third',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_time',
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='horse_first',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='votes_first', to='app1.horse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='horse_second',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='votes_second', to='app1.horse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='horse_third',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='votes_third', to='app1.horse'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='gamecomment',
            table='app1_comment',
        ),
        migrations.AlterModelTable(
            name='horse',
            table='app1_gameracehorse',
        ),

        migrations.AddField(
            model_name='horseplace',
            name='Horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.horse'),
        ),
        migrations.AddField(
            model_name='horse',
            name='Race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.race'),
        ),
        migrations.AddField(
            model_name='vote',
            name='race',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.race'),
            preserve_default=False,
        ),
    ]
