# Generated by Django 4.2.1 on 2023-08-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_race_joinresultodds'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamecomment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='horse',
            table=None,
        ),
    ]
