# Generated by Django 4.2.1 on 2023-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_gameplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerule',
            name='span',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
