# Generated by Django 4.2.1 on 2023-08-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_vote_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.game'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.race'),
        ),
    ]
