# Generated by Django 4.2.1 on 2023-09-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_vote_game_alter_vote_race'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinResultOdds',
        ),
        migrations.DeleteModel(
            name='Odds',
        ),
        migrations.DeleteModel(
            name='RaceResult',
        ),
    ]
