# Generated by Django 4.2.1 on 2023-09-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_odds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odds',
            old_name='renfuku_3',
            new_name='tierce',
        ),
        migrations.RenameField(
            model_name='odds',
            old_name='rentan_3',
            new_name='trio',
        ),
    ]
