# Generated by Django 4.2.1 on 2023-10-07 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_delete_racecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 7, 14, 45, 4, 984696, tzinfo=datetime.timezone.utc)),
        ),
    ]
