@startuml ER図

entity "RaceResult" as RaceResult {
  + id [PK]
  --
  horse_name
  horse_number
  race_name
  place_num
  jockey_name
  trainer_name
  time
  h_weight
  pop
  created_at
  ==
  レース結果
}

entity "Odds" as Odds {
  + id [PK]
  --
  horse_name
  horse_number
  race_name
  odds_tan
  odds_fuku_min
  odds_fuku_max
  created_at
  ==
  オッズ
}

entity "JoinResultOdds" as JoinResultOdds {
  + id [PK]
  --
  # RaceResult_id [FK]
  # Odds_id [FK]
  ==
  レース結果とオッズを紐づける
}

entity User {
  + UID [PK]
  --
  adress 
  username
  ==
  ゼロセンスユーザー
  ※Firebase上に用意
}

entity Game {
  + id [PK]
  --
  # GameRule_id [FK] NULL=TRUE
  # GameRace_id [FK]
  name
  start_datetime
  ==
  大会
}

entity GameRule {
  + id [PK]
  --
  rule_start_datetime
  rule_end_datetime
  open
  logic_id
  ==
  大会のルール
}

entity Vote {
  + id [PK]
  --
  # UID [FK]
  # Game_id [FK]
  horse_id_first
  horse_id_second
  horse_id_third
  vote_time
  comment
  ==
  投票
  投票時点で大会に参加
  ユーザーと 大会を紐づける
}

entity GameRace{
  + id [PK]
  --
  # JoinResultOdds_id [FK] NULL=TRUE
  race_name
  rank
  ==
  大会対象のレースと
  レース結果を紐づける
  ランクも取得する  
}

entity GameRaceHorse {
  + id [PK]
  --
  # GameRace_id [FK] NULL=TRUE
  horse_name
  ==
  大会の出走馬
}

entity Comment {
  + id [PK]
  --
  # Game_id [FK]
  # UID [FK]
  coment_text
  created_at
  ==
  大会に対するコメント
}

Game |o--|| GameRace
User ||--o{ Vote
Game ||--o{ Vote
GameRace ||-left-|{ GameRaceHorse
User ||--o{ Comment
Game ||--o{ Comment
GameRule ||--o{ Game
RaceResult ||--|| JoinResultOdds
Odds ||-|| JoinResultOdds
JoinResultOdds ||--o|GameRace

@enduml

