@startuml 20230920_ER図


entity HorsePlace {
  + id [PK]
  --
  # horse [FK]
  place
  ==
  レース結果
}

entity User {
  + id [PK]
  --
  # uid [FK]
  username
  ==
  ゼロセンスユーザー
}

entity FirebaseUser {
  + UID [PK]
  --
  adress 
  username
  ==
  Firebase上に用意している
  ゼロセンスユーザーDB
}

entity Game {
  + id [PK]
  --
  # game_rule [FK] NULL=TRUE
  name
  start_datetime
  ==
  大会
}

entity GameRule {
  + id [PK]
  --
  span
  open
  logic_id
  ==
  大会のルール
}

entity Vote {
  + id [PK]
  --
  # user [FK]
  # race [FK]
  # game [FK]
  # horse_first [FK]
  # horse_second [FK]
  # horse_third [FK]
  created_at
  comment
  ==
  投票
  投票時点で大会に参加
  ユーザーと大会を紐づける
}

entity Race{
  + id [PK]
  --
  race_name
  rank
  race_date
  is_votable
  ==
  投票対象のレース名
  grade(GⅢなど)を取得する  
  投票受付中ならis_votable
  が1終了なら0
}

entity Horse {
  + id [PK]
  --
  # race [FK] 
  horse_name NULL=TRUE
  ==
  大会の出走馬
}

entity Odds {
  + id [PK]
  --
  # race [FK]
  tan
  fuku_1
  fuku_2
  fuku_3
  umaren
  umatan
  wide_12
  wide_13
  wide_23
  trio
  tierce
  ==
  払い戻し金を取得する
}

entity GameComment {
  + id [PK]
  --
  # game [FK]
  # user [FK]
  comment_text
  created_at
  ==
  大会に対するコメント
}

entity GamePlayers {
  + id [PK]
  --
  # game [FK]
  # user [FK]
  ==
  大会の参加者を登録する
}

entity RaceComment {
  + id [PK]
  --
  # race [FK]
  # user [FK]
  comment_text
  created_at
  ==
  大会に対するコメント
}

Race ||--|| Odds
User ||--o{ Vote
Horse }--o{ Vote
Race ||--o{ Vote
Game ||--o{ Vote
Race ||--{ Horse
User ||--o{ GameComment
Game ||--o{ GameComment
User ||--o{ RaceComment
Race ||--o{ RaceComment
GameRule ||--o{ Game
HorsePlace ||--|| Horse
FirebaseUser ||..|| User
Game ||--|{ GamePlayers
User ||--o{ GamePlayers
@enduml

