# Generated by Django 4.2.1 on 2023-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=255)),
                ('horse_number', models.IntegerField()),
                ('race_name', models.CharField(max_length=255)),
                ('odds_tan', models.FloatField()),
                ('odds_fuku_min', models.FloatField()),
                ('odds_fuku_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=255)),
                ('horse_number', models.IntegerField()),
                ('race_name', models.CharField(max_length=255)),
                ('place_num', models.IntegerField()),
                ('jockey_name', models.CharField(max_length=255)),
                ('trainer_name', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('h_weight', models.FloatField()),
                ('pop', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='raceresult',
            constraint=models.UniqueConstraint(fields=('horse_number', 'race_name'), name='unique_race_result'),
        ),
        migrations.AddConstraint(
            model_name='odds',
            constraint=models.UniqueConstraint(fields=('horse_number', 'race_name'), name='unique_odds'),
        ),
    ]
