# Generated by Django 4.2.1 on 2023-06-17 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('app1', '0002_raceresult_created_at'), ('app1', '0003_odds_created_at')]

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odds',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
