# Generated by Django 4.2.1 on 2023-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_raceresult_created_at_squashed_0003_odds_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='odds',
            name='unique_odds',
        ),
        migrations.RemoveConstraint(
            model_name='raceresult',
            name='unique_race_result',
        ),
        migrations.AlterField(
            model_name='odds',
            name='horse_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='horse_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='odds_fuku_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='odds_fuku_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='odds_tan',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='race_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='h_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='horse_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='horse_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='jockey_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='place_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='pop',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='race_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='trainer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='odds',
            constraint=models.UniqueConstraint(fields=('horse_name', 'race_name'), name='unique_odds'),
        ),
        migrations.AddConstraint(
            model_name='raceresult',
            constraint=models.UniqueConstraint(fields=('horse_name', 'race_name'), name='unique_race_result'),
        ),
    ]
