# Generated by Django 4.2.1 on 2023-07-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_joinresultodds_horse_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinresultodds',
            old_name='Odds_id',
            new_name='Odds',
        ),
        migrations.RenameField(
            model_name='joinresultodds',
            old_name='RaceResult_id',
            new_name='RaceResult',
        ),
    ]
