# Generated by Django 4.2.1 on 2023-07-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_joinresultodds_odds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GameRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_start_datetime', models.DateTimeField()),
                ('rule_end_datetime', models.DateTimeField()),
                ('open', models.BooleanField()),
                ('logic_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField()),
                ('horse_id_first', models.IntegerField()),
                ('horse_id_second', models.IntegerField()),
                ('horse_id_third', models.IntegerField()),
                ('vote_time', models.DateTimeField()),
                ('comment', models.TextField()),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.game')),
                ('JoinResultOdds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.joinresultodds')),
            ],
        ),
        migrations.CreateModel(
            name='GameHorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=255)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='GameRule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.gamerule'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField()),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.game')),
            ],
        ),
    ]
