# Generated by Django 4.2.1 on 2023-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_gameresult_race_name_alter_gameresult_joinresultodds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='rank',
            field=models.CharField(max_length=255),
        ),
    ]
