# Generated by Django 4.2.1 on 2023-07-29 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_gameresult_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('JoinResultOdds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.joinresultodds')),
            ],
        ),
        migrations.CreateModel(
            name='GameRaceHorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=255)),
                ('Game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.gamerace')),
            ],
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='Game',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='JoinResultOdds',
        ),
        migrations.AlterField(
            model_name='game',
            name='GameRule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.gamerule'),
        ),
        migrations.DeleteModel(
            name='GameHorse',
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
        migrations.AddField(
            model_name='game',
            name='GameRace',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.gamerace'),
            preserve_default=False,
        ),
    ]
