# Generated by Django 4.2.1 on 2023-08-08 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_gamecomment_table_alter_horse_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='is_votable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='race_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
