# Generated by Django 4.2.1 on 2023-09-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_rename_renfuku_3_odds_tierce_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='GameRule',
            new_name='game_rule',
        ),
        migrations.RenameField(
            model_name='gamecomment',
            old_name='Game',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gamecomment',
            old_name='UID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='gameplayer',
            old_name='Game',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gameplayer',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='horse',
            old_name='Race',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='horseplace',
            old_name='Horse',
            new_name='horse',
        ),
        migrations.RenameField(
            model_name='odds',
            old_name='Race',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='racecomment',
            old_name='Race',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='racecomment',
            old_name='UID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UID',
            new_name='uid',
        ),
    ]
