# Generated by Django 4.2.1 on 2023-09-28 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_game_id_for_serch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerule',
            name='span',
        ),
        migrations.AddField(
            model_name='gamerule',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gamerule',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
