# Generated by Django 4.2.1 on 2023-10-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_remove_gamerule_span_gamerule_end_gamerule_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaceComment',
        ),
    ]
