# Generated by Django 4.2.6 on 2023-12-14 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_race_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 14, 14, 56, 6, 71266, tzinfo=datetime.timezone.utc)),
        ),
    ]
