# Generated by Django 4.2.6 on 2024-01-04 07:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_race_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseplace',
            name='horse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.horse'),
        ),
        migrations.AlterField(
            model_name='odds',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.race'),
        ),
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 4, 7, 16, 45, 542054, tzinfo=datetime.timezone.utc)),
        ),
    ]
