# Generated by Django 4.2.6 on 2024-01-04 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_alter_horseplace_horse_alter_odds_race_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='id_for_serch',
            new_name='id_for_search',
        ),
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 4, 19, 49, 30, 663147, tzinfo=datetime.timezone.utc)),
        ),
    ]
