# Generated by Django 4.2.6 on 2024-01-04 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_rename_id_for_serch_game_id_for_search_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='id_for_search',
            new_name='id_for_serch',
        ),
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 4, 20, 25, 38, 513801, tzinfo=datetime.timezone.utc)),
        ),
    ]
