name: Deploy

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Angularのビルド
      - name: Build Angular
        run: |
          cd angular_project_directory
          npm install
          ng build

      # 静的ファイルの収集
      - name: Collect static files
        run: python manage.py collectstatic --noinput

      # App Engineへのデプロイ
      - name: Deploy to App Engine
        run: gcloud app deploy
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

    # 必要に応じて環境変数や秘密情報を設定
    # secretsはGitHubリポジトリのSettings > Secretsで設定
