name: Deploy

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
  # 実行環境の指定
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
# python環境のインストール
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # DB設定のインポート
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}

      # Angularのビルド
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build Angular
        run: |
          cd angular_app_sourse
          npm install
          ng build

# 静的ファイルの収集
      - name: Collect static files
        run: |
          ls
          python manage.py collectstatic --noinput

      # App Engineへのデプロイ
      - name: Deploy to App Engine
        run: gcloud app deploy -q
