name: Deploy

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    # 実行環境の指定
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    # python環境のインストール
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # DB設定のインポート
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}

      # Angularのビルド
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build Angular
        run: |
          cd angular_app_sourse
          npm install
          ng build

      # 静的ファイルの収集
      - name: Collect static files
        run: |
          ls
          python manage.py collectstatic --noinput

      - name: Create .env
        run: |
          echo "runtime: python39" > .env
          echo "env_variables:" >> .env
          echo "  DATABASE_NAME: '${{ secrets.DATABASE_NAME }}'" >> .env
          echo "  DATABASE_USER: '${{ secrets.DATABASE_USER }}'" >> .env
          echo "  DATABASE_PASSWORD: '${{ secrets.DATABASE_PASSWORD }}'" >> .env
          echo "  DATABASE_HOST: '${{ secrets.DATABASE_HOST }}'" >> .env
          echo "  DATABASE_PORT: '${{ secrets.DATABASE_PORT }}'" >> .env
          echo "  DJANGO_DEBUG: '${{ secrets.DJANGO_DEBUG }}'" >> .env

      # GCPキーを作成

      - name: Auth with Google Cloud
        run: |
          echo "${{ secrets.GCLOUD_AUTH }}" > gcloud.json
          gcloud auth activate-service-account --key-file=gcloud.json

      # App Engineへのデプロイ
      - name: Deploy to App Engine
        run: gcloud app deploy -q
